analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal: []
  indicator: []
  post: []
cookie_consent_form:
  enabled: false
country:
  name: Kazakhstan
  adjective: Kazakh
create_goals:
  previous_next_links: false
  goal_content_heading: ''
  goals: []
create_indicators:
  previous_next_links: false
  layout: indicator
create_pages:
  - filename: ''
    folder: /
    layout: frontpage
    title: ''
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: status.reporting_status
  - filename: indicators.json
    folder: /
    layout: indicator-json
    title: ''
  - filename: ''
    folder: /search
    layout: search
    title: search.search
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: >-
  https://github.com/kazstat/sdg-data-kazstat/blob/develop/data/indicator_[id].csv
data_fields:
  units: UNIT_MEASURE
  series: SERIES
date_formats: []
disclaimer:
  phase: ''
  message: ''
  hidden: false
email_contacts:
  questions: ai.dosanova@economy.gov.kz
  suggestions: as.abraeva@economy.gov.kz
  functional: ai.dosanova@economy.gov.kz
empty_metadata_placeholder: ''
empty_metadata_placeholder_sources: ''
environment: staging
footer_language_toggle: none
footer_menu:
  - path: 'mailto:ai.dosanova@economy.gov.kz'
    translation_key: menu.contact_us
  - path: 'https://facebook.com/statgov.kz'
    translation_key: general.facebook
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
frontpage_goals_grid:
  title: custom.frontpage_heading
  description: custom.frontpage_instructions
frontpage_introduction_banner:
  title: custom.frontpage_intro_title
  description: custom.frontpage_intro_description
goal_image_base: 'https://open-sdg.github.io/sdg-translations/assets/img/goals'
goal_image_extension: ''
goals_page:
  title: ''
  description: ''
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
graph_title_from_series: false
header_language_toggle: dropdown
hide_empty_metadata: false
hide_single_series: false
hide_single_unit: false
ignored_disaggregations: []
indicator_config_form:
  enabled: true
  dropdowns:
    - jsonschema: reporting_status
      values:
        - complete
        - notstarted
        - notapplicable
      labels:
        - Опубликован
        - В процессе разработки
        - Непригодный
  repository_link: 'https://github.com/kazstat/sdg-data-kazstat/tree/develop/indicator-config'
  translation_link: >-
    https://hosted.weblate.org/search/sdgs-kazakhstan/[group]/?q=+context%3A%3D[key]
indicator_data_form:
  enabled: false
  repository_link: ''
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: 'https://github.com/kazstat/sdg-data-kazstat/tree/develop/meta'
  translation_link: >-
    https://hosted.weblate.org/search/sdgs-kazakhstan/[group]/?q=+context%3A%3D[key]
  language: ru
  scopes:
    - global
    - national
    - source_1
  exclude_fields:
    - national_metadata_update_url
    - national_metadata_update_url_text
    - national_data_update_url
    - national_data_update_url_text
  translated: false
indicator_tabs:
  tab_1: ''
  tab_2: ''
  tab_3: ''
  tab_4: ''
languages:
  - kk
  - ru
  - en
languages_public:
  - language: kk
    language_public: kz
logos: []
map_layers:
  - subfolder: ''
    label: REF_AREA.REF_AREA
    min_zoom: 3
    max_zoom: 10
    staticBorders: false
map_options:
  disaggregation_controls: false
  minZoom: 3
  maxZoom: 10
  tileURL: >-
    https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}
  tileOptions:
    id: mapbox.light
    accessToken: >-
      pk.eyJ1IjoiYnJvY2tmYW5uaW5nMSIsImEiOiJjaXplbmgzczgyMmRtMnZxbzlmbGJmdW9pIn0.LU-BYMX69uu3eGgk0Imibg
    attribution: '<a href="https://www.mapbox.com">Mapbox</a>'
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: '5,5'
menu:
  - path: /reporting-status
    translation_key: menu.reporting_status
    dropdown: []
  - path: /about
    translation_key: menu.about
    dropdown: []
  - path: /faq
    translation_key: menu.faq
    dropdown: []
metadata_edit_url: metadata
metadata_tabs: []
meta_tags: []
news:
  category_links: false
observation_attributes: []
progress_status:
  status_heading: ''
  status_help: ''
  status_types: []
progressive_web_app:
  enabled: false
  name: ''
  short_name: ''
  precaching: false
proxy_indicators:
  label: ''
  description: ''
remote_data_prefix: 'https://kazstat.github.io/sdg-data-kazstat'
reporting_status:
  title: ''
  description: ''
  disaggregation_indicator_count_label: ''
  disaggregation_tabs: false
  status_types:
    - value: complete
      label: status.reported_online
      hide_on_goal_pages: false
    - value: notstarted
      label: status.exploring_data_sources
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
repository_url_data: ''
repository_url_site: ''
search_index_boost:
  - field: title
    boost: 10
  - field: indicator_available
    boost: 15
search_index_extra_fields:
  - indicator_available
  - source_compilation_1
  - source_data_1
  - source_implementation_1
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: 'https://github.com/kazstat/sdg-site-kazstat/tree/develop/_data'
  translation_link: >-
    https://hosted.weblate.org/search/sdgs-kazakhstan/[group]/?q=+context%3A%3D[key]
time_series_attributes:
  - field: COMMENT_TS
    label: indicator.footnote
  - field: DATA_LAST_UPDATE
    label: metadata_fields.national_data_update_url
use_new_config_forms: false
validate_indicator_config: false
validate_site_config: false
x_axis_label: ''
